### ISSUE TITLE
Add desktop entries

### ISSUE THREAD

**Issue by imnotrev** [anufrievroman/waypaper#10]
I usually use rofi to open apps. A desktop entries could be useful for a gui app

**Comment by anufrievroman** [comment]
I thought about it as well, would be great. By chance, do you know some other python app with a desktop entry so that we could use it as an example?

**Comment by imnotrev** [comment]
I dunno, just made this up in my head

**Comment by imnotrev** [comment]
BUT This would probably help:
https://askubuntu.com/questions/342950/how-do-i-create-a-desktop-entry-to-launch-a-python-script

**Comment by imnotrev** [comment]
I have no idea of how to do this, got no python experience :v

**Comment by kekonn** [comment]
If you already have a .desktop, a safe place to install it on most distributions is `~/.local/applications`. On Arch, system wide .desktop files go in `/usr/share/applications`.

An svg icon would go in `/usr/share/icon/hicolor/scalable`

**Comment by imnotrev** [comment]
That's right, but i think he does know that. What he probably _doesn't_ know is how to put that files on `~/.local/share/applications` or `/usr/share/applications`

**Comment by anufrievroman** [comment]
Yes, I suppose whoever maintains AUR package should do it AUR way, the same for NIX, and I need to figure it out how to do it for Pypi.

**Comment by Thaodan** [comment]
> I mean, sure, I've [included .desktop and .svg icons](https://github.com/anufrievroman/waypaper/tree/main/data), it's just that I am not sure how to set up it all so that it integrates into every system. You can try to install the most recent version from Pypi but to me it does not seem to be working.

Those look good just the `entry_points` is slightly wrong, you should use "gui_scripts"
 instead of "console_scripts".

**Comment by anufrievroman** [comment]
So, in the PR from @Thaodan the .desktop is installed to `share/applications`, but at least on my system it does not really work. Shouldn't it be `usr/share/applications` or `usr` is implied by the installation? Or maybe the `setup.py` should attempt to install it into several locations?
Please try if the version that is currently on Pypi has the desktop entry and icon.

**Comment by Thaodan** [comment]
> So, in the PR from @Thaodan the .desktop is installed to `share/applications`, but at least on my system it does not really work. Shouldn't it be `usr/share/applications` or `usr` is implied by the installation? Or maybe the `setup.py` should attempt to install it into several locations? Please try if the version that is currently on Pypi has the desktop entry and icon.

How did you install the package?

**Comment by Thaodan** [comment]
Setuptools docs say [this](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#data-files):
> Each (directory, files) pair in the sequence specifies the installation directory and the files to install there. The directory must be a relative path (although this may change in the future, see [wheel Issue #92](https://github.com/pypa/wheel/issues/92)), and it is interpreted relative to the installation prefix (Python’s sys.prefix for a default installation; [..]

**Comment by anufrievroman** [comment]
I realized that since I use `pipx` the application is installed into virtual environment and the files are installed there. It looks like my system does not see it there, but it's likely the problem specific to `pipx` or my particular system (I actually don't even have graphical launchers). I believe your PR was correct :)

**Comment by Thaodan** [comment]
You should try to open a python shell in that environment an run:
import sys
sys.prefix

Good that everything is fine now :)

**Comment by imnotrev** [comment]
closing this issue since it works now
