### ISSUE TITLE
Setting wallpaper of one monitor clears the other

### ISSUE THREAD

**Issue by derekfrogget** [anufrievroman/waypaper#104]
I'm on Hyprland with swaybg, with waypaper installed via the AUR.

With the new version of waypaper, 2.4, multi monitor support was introduced for swaybg. However, upon selecting a monitor and clicking on a wallpaper for it, the other monitor's wallpaper turns black (not the background color, either, always black). 

Expected behavior: I select a monitor, click a wallpaper, and that wallpaper is applied to selected monitor only, leaving other monitors with the wallpaper they had before.

Actual behavior: I select a monitor, click a wallpaper, and that wallpaper is applied to the selected monitor, but other monitors turn black.

**Comment by anufrievroman** [comment]
Thank you for reporting. And in your configs/waypaper/config.ini file, what is written for wallpaper and monitors variables? There should be multiple entries one for each monitor.

I mean, the only situation when I can imagine this happening, is when you set the first wallpaper for the first monitor (i.e. nothing is assigned to another). I'll retest this today...

**Comment by anufrievroman** [comment]
Actually, nevermind my comment above. You are right, it happens no matter what because we killall previous swaybg processes. Need to find a way not to kill those that are running on other monitors...

**Comment by anufrievroman** [comment]
Probably fixed that issue in 855aca2951f95efc53baeac9a20043c80d6f983a, but need to test more.

**Comment by anufrievroman** [comment]
Okay, I think it works now. So, I close this.
