### ISSUE TITLE
Add a new parameter to implement --restore without running post_command.

### ISSUE THREAD

**Issue by acdcbyl** [anufrievroman/waypaper#106]
I'm not sure how many people need this feature. I wrote a component using `zenity` and `matugen` to switch between dark and light colours when selecting a wallpaper, but it being called by waypaper when restarting the PC is of no use to me. Maybe a new parameter is needed. Anyway, thanks to the developer - waypaper is the best wallpaper front end to use.

**Comment by anufrievroman** [comment]
Hi, thank you! Yes, I see how running post command every time might be problematic in some cases. I'll implement `--no-post-command` argument, which you can use in addition to `--restore`.

**Comment by anufrievroman** [comment]
Okay, done it in 723e1c296a9d06fdcec5837d61ca4326c63d63c7
If you have time, please try from the main branch as `waypaper --restore --no-post-command`

**Comment by acdcbyl** [comment]
Wow, thank you so much, I will try it right away!
