### ISSUE TITLE
2.0.1 isn't tagged in git

### ISSUE THREAD

**Issue by Thaodan** [anufrievroman/waypaper#13]
2.0.1 is available in pypi but not tagged here.

**Comment by anufrievroman** [comment]
Is it problematic for packing or something? I mean, I often push small improvements to git and repos, but tag only somewhat big changes. I don't know if it may create a conflict.

**Comment by Thaodan** [comment]
If you push a new realease to pypi it should be also tagged in git.
Each version should have a tag. So yeah it's problematic for packaging.

Eventually you can also use the ci to e.g. push a release to pypi on
each git tag that you publish.

Also it's handy for users and packagers to watch the project for new
releases/git tags.

**Comment by anufrievroman** [comment]
Okay, I didn't know that. Thanks. I've created tad 2.0.2 and corresponding release on pypi. I'll try to keep it clean in the future.

**Comment by Thaodan** [comment]
Thanks.
