### ISSUE TITLE
Support the webp images

### ISSUE THREAD

**Issue by Gigas002** [anufrievroman/waypaper#19]
`eww` backend supports `.webp` as bg images, but `waypaper` seems to show only `.png` files in directory. Would be great to see these in directory view too.

**Comment by anufrievroman** [comment]
At the moment, only extensions common to all backends are supported '.gif', '.jpg', '.jpeg', '.png' and to make backend specific lists I'll need to rewrite some parts. The `eww` is not really supported as a backend, I didn't know it can do something like this. So, unless you mixed up the name of the backend, I don't think it will be implemented.

**Comment by Gigas002** [comment]
Ah, sorry, my bad. I meant `swww`. Always mess with these two...

**Comment by anufrievroman** [comment]
> Ah, sorry, my bad. I meant `swww`. Always mess with these two...

No problem :D I'll see how to better implement it.

**Comment by anufrievroman** [comment]
Hi, I implemented the support for webp and some other formats under `swww`. It will be available in 2.0.3 soon. Happy new year!

**Comment by Gigas002** [comment]
Awesome, thanks! Happy new year!
