### ISSUE TITLE
Sort order

### ISSUE THREAD

**Issue by mausworks** [anufrievroman/waypaper#2]
Having a large wallpaper directory (see #1) it would be nice to be able to change how the wallpapers are sorted. I.e.:

1. By date created or modified
3. By name

Nitrogen supported this feature, and it was really handy!

**Comment by anufrievroman** [comment]
Yes, I started working in this direction, it will be available in the next version I think.

**Comment by anufrievroman** [comment]
Okay, it was not too difficult :) In version 1.7 sorting is possible:

![image](https://github.com/anufrievroman/waypaper/assets/42904990/018ad0d2-aaab-42d7-acea-77ca061d1352)

**Comment by mausworks** [comment]
Beautiful! Updated, and it works great. :heart:
