### ISSUE TITLE
No module named 'PIL'

### ISSUE THREAD

**Issue by OfficialCRUGG** [anufrievroman/waypaper#22]
Hey there! Just installed waypaper from AUR on a relatively fresh Arch install and faced this error:
```
Traceback (most recent call last):
  File "/usr/bin/waypaper", line 5, in <module>
    from waypaper.__main__ import run
  File "/usr/lib/python3.11/site-packages/waypaper/__main__.py", line 8, in <module>
    from waypaper.app import App
  File "/usr/lib/python3.11/site-packages/waypaper/app.py", line 10, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```

I assume I need to install this module, but through what? Also it'd probably be good to have the respective instructions for this in the Readme.

**Comment by anufrievroman** [comment]
Ooops, strange, I thought it will install everything needed. Yes, it is a new dependence `Pillow` library. On arch you can install as:
```
pacman -S python-pillow
```
But I'll investigate why it does not autoinstall...

**Comment by OfficialCRUGG** [comment]
Thanks, works now!

**Comment by anufrievroman** [comment]
I think now AUR kind of updated the build, so from now on it should be okay to everybody. Not sure why there is some kind of lag between updating the build file and repository.

**Comment by anufrievroman** [comment]
Okay, I think it's fixed now, so I'll close this issue. Thank you for reporting!
