### ISSUE TITLE
No longer able to set wallpaper

### ISSUE THREAD

**Issue by CountMurphy** [anufrievroman/waypaper#27]
Just updated to the latest commit (3f2fe2c838de864cbe4cce7db71429b9a1da143c). Trying to change or set the wallpaper results in 
```
Error changing wallpaper: name 'color' is not defined
```

using swaybg as the backend, and swaybg works if I call it directly.

**Comment by Mato1111** [comment]
Same issue here, also using swaybg. I also was not able to use the 'random' button' before i updated to this commit.

**Comment by anufrievroman** [comment]
Oops, my bad, missed a little thing. Just updated, please try.

**Comment by Mato1111** [comment]
swaybg is working :+1: 
Thanks!
