### ISSUE TITLE
cannot execute sequential commands as post_command

### ISSUE THREAD

**Issue by JunkyJohnny667** [anufrievroman/waypaper#31]
Was trying to configure my post_command in config.ini such that pywal grabs the selected wallpaper, and then pywalfox is updated. The command I used is this:
```
post_command = wal -i $wallpaper && pywalfox update
```
Doing this however causes both of these commands to fail. I should note that having the post_command just be "wal -i $wallpaper" works as expected, and that running the same combo command manually (swapping out the $wallpaper variable for path/to/img, i.e "wal -i path/to/img && pywalfox update") also works exactly as expected

**Comment by anufrievroman** [comment]
Yes, I see, it does not recognize && as comand separator...
```
echo "Hello" && echo "World" executed
"Hello" && echo "World"
```
I'll see what could be done.

**Comment by anufrievroman** [comment]
Okay, fixed that.

**Comment by JunkyJohnny667** [comment]
Hi, this did fix the issue described, but it also broke my keybind to open waypaper and the exec_once = waypaper --restore command in my hyprland.conf. I had previously installed waypaper through the AUR but uninstalled it and replaced it with the pip install to test this, I highly doubt that's relevant since it really shouldn't break something like that but just in case

**Comment by JunkyJohnny667** [comment]
Update: uninstalling the pipx package and reinstalling the AUR package has fixed that new issue. It has brought about another weird issue where pywal isn't detecting images with a numerated filename (eg. selecting wallpaper.jpg through waypaper does trigger the pywal command whereas selecting wallpaper(1).jpg causes the pywal command to fail. Luckily that's an issue that can be solved by me just bothering to organise my wallpapers.

**Comment by anufrievroman** [comment]
Thank you for testing! I'll close this issue then. I think AUR calcure-git package should work too since it syncs with main.
