### ISSUE TITLE
Custom backend command

### ISSUE THREAD

**Issue by musjj** [anufrievroman/waypaper#33]
It'd be nice if we can provide a custom command/script for the backend.

For example if you wanted to have a custom random transition with `swww`, you can specify a script to the config:

```bash
# Picks a random corner to start the transition from
swww img \
  -t $(shuf -n 1 <<<$'grow\nouter') \
  --transition-pos $(shuf -n 1 <<<$'top-left\ntop-right\nbottom-right\nbottom-left') \
  $1 # the passed image
```

**Comment by anufrievroman** [comment]
It's an interesting idea and the `post_command` option  in config almost does that, except that waypaper will always issue its own command to change the wallpaper. So, the most elegant solution that I see is to introduce the possiblity to select `None` as backend, and then waypaper will work just as filepicker and your `post_command` script will do all the job.

**Comment by anufrievroman** [comment]
Implemented this in main. Now, if you chose `none` backend, the waypaper will not try to issue a backend command but only execute a `post_command` from config, there you can write any script that uses `$wallpaper` variable.

**Comment by anufrievroman** [comment]
I'll consider this issue resolved then.
