### ISSUE TITLE
Waypaper can no longer set wallpaper

### ISSUE THREAD

**Issue by CountMurphy** [anufrievroman/waypaper#34]
Since updating to 2.1.r7 the wallpaper fails to change. Running `waypaper --restore --random` produces `swaybg: no process found.` I do have swaybg installed. Downgrading to 2.1.r6 fixes the issue. Currently running Arch linux if that makes any difference.

**Comment by anufrievroman** [comment]
Thank you for reporting. And the backend you are trying to use is swaybg or some other one?

**Comment by anufrievroman** [comment]
Okay, I could reproduce your problem. I am not sure the exact problem yet, but it's because AUR's waypaper-git builds from main, which is currently a bit messy. I recommend installing with `pipx install waypaper` which is more stable. I'll look into it in the next few days.

**Comment by anufrievroman** [comment]
I think it's fixed. Please try to reinstall from AUR with clean build all.

**Comment by CountMurphy** [comment]
Seems fixed to me. Thanks!
