### ISSUE TITLE
post_command $wallpaper doesn't work properly if spaces are in filename

### ISSUE THREAD

**Issue by enjoyerofcode** [anufrievroman/waypaper#36]
When a wallpaper has a space in it's filename $wallpaper doesn't treat it as a whole string and treats it as separate arguments.
`wallpaper = /path/to/wall paper.png`
`post_command = wallust run $wallpaper`
In this scenario the command it runs will be `wallust run /path/to/wall paper.png` (all wallust gets is `/path/to/wall`), which will make the command not work correctly as it doesn't know the full path to the wallpaper. I would imagine a fix to this would just be to wrap it in quotes so it's treated as a string and not separate arguments, ie: `wallust run "/path/to/wall paper.png"` which will work properly as wallust will know it's a string.

**Comment by anufrievroman** [comment]
To me it's more a problem of `wallrust` that it doesn't understand the path with quotes. If I wrap in quotes the path for everyone, some other programs might not like the quotes, so I am not sure about this solution. Could you please try just writing your post command as `wallust run " $wallpaper "` ?

**Comment by anufrievroman** [comment]
Good idea! Just fixed it the way you suggested. It works for me now. Please try by installing from the main branch of from AUR

**Comment by enjoyerofcode** [comment]
Thank you this works!

**Comment by shadowe1ite** [comment]
issue still persist . i tried -git version

![Image](https://github.com/user-attachments/assets/ff98b2fd-6c54-492c-95b5-eb567e1bea21)

@anufrievroman
