### ISSUE TITLE
Restarting waybar in post-command causes waypaper interface to freeze

### ISSUE THREAD

**Issue by JunkyJohnny667** [anufrievroman/waypaper#37]
OS: Arch
my post-command in config.ini is currently "wal -i $wallpaper && pywalfox update && killall waybar && waybar". The last two commands are intended to simply restart waybar as it's colour scheme doesn't automatically update to match that created by pywal. Running waypaper with this config does execute the commands succesfully, but after this the interface for waypaper completely freezes and it cannot be closed, neither by clicking exit or by using my keybind for closing the focused program. I have tried putting the commands related to waybar into a simple script and adding said script to the post-command, eg. "wal -i $wallpaper && pywalfox update && sh /path/to/script/launch.sh", however this causes the exact same behaviour from waypaper.

**Comment by anufrievroman** [comment]
Thank you for reporting. I think I may know why. I tried to do a little fix in the last commit. Could you try to reinstall from main?
```
pipx install git+https://github.com/anufrievroman/waypaper
```

**Comment by JunkyJohnny667** [comment]
Apologies for the late reply, good news is this now works. The bad news is that now my keybind to launch waypaper doesn't work

**Comment by anufrievroman** [comment]
This sometimes happens when people install from git instead of the official ways. It may help to delete all other installations of waypaper. I'll try to package this and other small improvements into a new release soon.

**Comment by anufrievroman** [comment]
I assume this issue is fixed then.

**Comment by UjeNeTORT** [comment]
I have just the same problem right now. 
post_command = wal -i $wallpaper

and after wallpaper change waypaper interface freezes and wont close
