### ISSUE TITLE
Add the ability to hide wallpapers

### ISSUE THREAD

**Issue by NyanMaths** [anufrievroman/waypaper#38]
Hello,
The problem is simple : I would like the gui to hide all wallpapers whose name starts with a dot likewise all files managers and be able to toggle the visibility with a menu or ctrl+h.
It could also be useful to have an option like "hide wallpaper" on right-click to add it to a hide-list without needing to make the filename start with a dot.
... _I have no dubious wallpaper at all, what do you mean ?_
Thanks in advance for any answer.

**Comment by anufrievroman** [comment]
Hi, thank you for the suggestion! Yes, it makes sense. I think I'll at least implement the show/hide the hidden wallpapers. 

However, the hiding of certain wallpapers without actually making them hidden in the operating system would require a big overhead and a separate black list stored somewhere and the ability to remove images from there. I just don't think this niche feature is worth it. So I can only propose hiding certain wallpapers from the list just by renaming them with right click, i.e. they will become hidden in the operating system too, that is quite simple.

**Comment by NyanMaths** [comment]
Hmmmmm, nice !
And I have to admit that the "hide" feature indeed was a bit overkill.
Thank you again for this awesome software.

**Comment by anufrievroman** [comment]
By the way, in the last version, the toggle for hidden images with `.` is implemented.

**Comment by anufrievroman** [comment]
Hidden folders are implemented as well. So, I'll consider this issue close. Thank you again for bringing this up.

**Comment by NyanMaths** [comment]
As late as it is, thank you for implementing !
I also searched the web about ctrl+h and did not find...
