### ISSUE TITLE
Dynamic or user configurable column count for displaying images in main window.

### ISSUE THREAD

**Issue by SherLock707** [anufrievroman/waypaper#43]
Instead of fixed 3 column of images can we get number of column based on app window size (_can be based on launched window size or dynamic update upon resiz_e) or based on a user config value?

![image](https://github.com/anufrievroman/waypaper/assets/26952545/04f18c2a-0aab-4dcc-b57d-b772af674a9c)

Awesome app! Thank you for your hardwork.

**Comment by anufrievroman** [comment]
Hi, I tried to achieve the scaling automatically for a while, but that just never worked for me. Maybe someone more knowledgeable about GTK could advise. However, I like the idea of putting the number of columns in the config, I'll try this approach.

**Comment by anufrievroman** [comment]
So, I managed to implement it, now the config parameter `number_of_columns = 3` should be able to control it. You can test in by installing from the main. It will be available in the next version.
![20240512_13h40m03s_grim](https://github.com/anufrievroman/waypaper/assets/42904990/bb48fe06-3c5f-4010-a99a-19321b12f30e)

**Comment by SherLock707** [comment]
> So, I managed to implement it, now the config parameter `number_of_columns = 3` should be able to control it. You can test in by installing from the main. It will be available in the next version.
> ![20240512_13h40m03s_grim](https://github.com/anufrievroman/waypaper/assets/42904990/bb48fe06-3c5f-4010-a99a-19321b12f30e)
> 

Oh wow! That was quick! Thanks. Can't wait to try it out.

**Comment by SherLock707** [comment]
How do I build and run it?
I tried:
`python3 setup.py build`
`python3 setup.py install`


![image](https://github.com/anufrievroman/waypaper/assets/26952545/e152ca2b-e660-4b92-b911-46178f5bd6aa)

**Comment by SherLock707** [comment]
Off-topic: When I set a wallpaper, is there any way I can get name/path of that image file? 
_Need to send that path to pywall or any script to do some stuff_

**Comment by SherLock707** [comment]
> Off-topic: When I set a wallpaper, is there any way I can get name/path of that image file? _Need to send that path to pywall or any script to do some stuff_

Figured out. thanks.

config : `post_command = notify-send $wallpaper`

**Comment by anufrievroman** [comment]
> How do I build and run it? I tried: `python3 setup.py build` `python3 setup.py install`
Two simple ways are: `yay -S waypaper-git` (if you are on Arch) or `pipx install git+https://github.com/anufrievroman/waypaper`

**Comment by SherLock707** [comment]
> > How do I build and run it? I tried: `python3 setup.py build` `python3 setup.py install`
> 
> Two simple ways are: 
> 
> `yay -S waypaper-git` (if you are on Arch)
> 
> `pipx install git+https://github.com/anufrievroman/waypaper`

Thanks, and how do I build it from repo?

**Comment by anufrievroman** [comment]
As far as I understand, you don't really build it, setup script just puts python files into corresponding folders. For example, if you cloned it, you can run it from the repo folder directly as `python -m waypaper`.

p.s. there might be errors due to missing package meta data, so to use this method you'd need to have some version of waypaper installed globally in your system.

**Comment by SherLock707** [comment]
> As far as I understand, you don't really build it, setup script just puts python files into corresponding folders. For example, if you cloned it, you can run it from the repo folder directly as `python -m waypaper`.
> 
> p.s. there might be errors due to missing package meta data, so to use this method you'd need to have some version of waypaper installed globally in your system.

Oh cool, understood. Thanks
