### ISSUE TITLE
Support '~' in config

### ISSUE THREAD

**Issue by SherLock707** [anufrievroman/waypaper#44]
### [Enhancement]

Can you please add support for ~ expansion in config read?

![image](https://github.com/anufrievroman/waypaper/assets/26952545/8052a7dd-46cc-43c5-935b-e0ab3fb8d4a7)

You can check if path string contains `~` , if so `os.path.expanduser(path)`

While writing back to the config you can override the ~ with actual home path.

_Just trying to make if username independent when installing dots on fresh install.._

**Comment by anufrievroman** [comment]
I didn't bother to do it because initially, the user were not supposed to mess with config file as it is updated by the program. But I see that people do it anyway :D So, I'll add the path expansion on occasion.

**Comment by anufrievroman** [comment]
Implemented in 721cbe7bfb8b799c134d4b1c6674e0b0ed3ae9cf
