### ISSUE TITLE
it appears that the swww backend still uses swww init, which is deprecated.

### ISSUE THREAD

**Issue by hfytr** [anufrievroman/waypaper#56]
waypaper version 2.1
swww version 0.9.5
When running`waypaper --backend swww` I get `
DEPRECATION WARNING: swww init IS DEPRECATED. Call swww-daemon directly instead`
Its not critical, but I suggest switching to swww-daemon sooner or later.

**Comment by nikolaizombie1** [comment]
Versions 2.1.2 and 2.2 utilize `swww-daemon` and not `swww init`.

**Comment by anufrievroman** [comment]
I'll close this then as it appears @hfytr just didn't update yet.
