### ISSUE TITLE
[Arch, Sway] Waypaper no longer launches

### ISSUE THREAD

**Issue by amberjennings** [anufrievroman/waypaper#61]
Log is attached. This issue began a few days ago after a normal `pacman -Syu`.
[log.txt](https://github.com/user-attachments/files/16046842/log.txt)
This is waypaper-git installed via AUR.
Let me know if I can provide more detail, thanks.

**Comment by anufrievroman** [comment]
Thank you for reporting. Not sure what the problem it. Could you try to just run `swww query` in your terminal? You should see the plugged monitors, but it seems like that part breaks for some reason.

**Comment by amberjennings** [comment]
I still get the `Error: "failed to write serialized request: Broken pipe (os error 32)"`. I've reinstalled `swww` to no avail.
I do see this issue reported earlier today in swww's repo: https://github.com/LGFae/swww/issues/337

**Comment by amberjennings** [comment]
I've swapped from swww-git over to the stable swww and things seem to be working. I'll re-raise this issue in the swww repository. Thanks!
