### ISSUE TITLE
Update wallpaper (hyprpaper) with single image using waypaper command

### ISSUE THREAD

**Issue by mylinuxforwork** [anufrievroman/waypaper#66]
Hi. 

Maybe someone could help me. I have waypaper configured with hyprland. Every is working fine.

What is the correct way to update the wallpaper with a single image from a bash script? Is there a way to do this with a waypaper command?

Setting a random wallpaper works fine but I haven't found the way in the documentation to select a wallpaper without using the GUI.

Any ideas?

**Comment by anufrievroman** [comment]
That's a good idea. At the moment there's no cli option to do that, but I can see how it might be useful. I'll implement that.

**Comment by mylinuxforwork** [comment]
> That's a good idea. At the moment there's no cli option to do that, but I can see how it might be useful. I'll implement that. 

That would be great. Thanks a lot.

**Comment by anufrievroman** [comment]
I implemented this feature, so that `waypaper --wallpaper path/to/image.jpg` sets a new wallpaper without GUI and saves it in the config. It is now available in main branch and will be in the next version.

**Comment by mylinuxforwork** [comment]
That is great. Looking forward to the next AUR release.
