### ISSUE TITLE
Mutiple command on post command ?

### ISSUE THREAD

**Issue by kito30** [anufrievroman/waypaper#67]
I am curious about is it a possible way to execute 2 command in the post command. For instance wal -i $wallpaper and wpg -s $wallpaper

**Comment by anufrievroman** [comment]
In principle, all instances of $wallpaper should be replaced with the path, so there should be no problem with writing `wal -i $wallpaper && wpg -s $wallpaper`, but I didn't test. 

In general, if you are looking to implement complex behavior, it's more practical to write a separate small script and execute it via post_command.

**Comment by anufrievroman** [comment]
I will assume this is resolved then
