### ISSUE TITLE
Feature: Add search to gui application to filter images

### ISSUE THREAD

**Issue by mylinuxforwork** [anufrievroman/waypaper#68]
Hi,

In the current version you’re showing all images as previews in alphabetical order. In case of a large collection it’s difficult to find the right image just by scrolling.

That’s why I request a search function implemented as a search field above the thumbnails to filter the images by filename. The list should get filtered everytime I  type a character in.

Thank you for considering this feature.

**Comment by anufrievroman** [comment]
Sounds useful, but personally, I have no idea how to code, especially so that it gets filtered upon entering every new character. I'll check, maybe there's some standard GTK implementation available for search...

**Comment by chrissolanilla** [comment]
> Hi,
> 
> In the current version you’re showing all images as previews in alphabetical order. In case of a large collection it’s difficult to find the right image just by scrolling.
> 
> That’s why I request a search function implemented as a search field above the thumbnails to filter the images by filename. The list should get filtered everytime I type a character in.
> 
> Thank you for considering this feature.

Hello, I have some experience in doing filtering in programming and would be willing to implement this feature if you have not already. I like your Hyprland dotfiles btw. Currently I have some experience in adding one feature to this project and I think it's a great idea.

**Comment by anufrievroman** [comment]
> Currently I have some experience in adding one feature to this project and I think it's a great idea.

Sure, please. On the side note, I think re-filtering upon every new letter might be too much as the library of images are sometimes too large and it might be difficult to reload all thumbnails. So it's better to start with just a search after hitting enter.

**Comment by Reyshyram** [comment]
> re-filtering upon every new letter might be too much as the library of images are sometimes too large and it might be difficult to reload all thumbnails

Maybe re-filtering after a certain amount of time has passed without an user input (like 250ms) would be a solution?

**Comment by Sandesh2007** [comment]
I am working on the search image feature and it is almost done.
I also added menu for swww options.

**Preview**

https://github.com/user-attachments/assets/57038874-4372-456a-ac91-b5d360143d79

**Comment by Sandesh2007** [comment]
I am working on the search image feature and it is almost done.
I also added menu for swww options.

**Preview**

https://github.com/user-attachments/assets/1177a195-4c85-4230-a2c9-3e9138629ef7

**Comment by anufrievroman** [comment]
Thanks to @Sandesh2007 this feature is implemented. Thank you all for suggestions and contributions. The feature will be available in the next release. But don't hesitate to install `waypaper-git` or from the main branch to test it.

**Comment by mylinuxforwork** [comment]
@anufrievroman @Sandesh2007 Awesome. Thank you so much for this great improvement.
