### ISSUE TITLE
Fedora 40: pip seemed to fail to build packages

### ISSUE THREAD

**Issue by tom-avilius** [anufrievroman/waypaper#72]
### Error log
pipx install waypaper
Fatal error from pip prevented installation. Full pip output in file:
    /home/tom-avilius/.local/state/pipx/log/cmd_2024-08-25_00.35.47_pip_errors.log

pip seemed to fail to build packages:
    installable
    pycairo

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    cairo/bufferproxy.c:32:10: fatal error: Python.h: No such file or directory
    error: command '/usr/bin/gcc' failed with exit code 1
    ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pycairo)

Error installing waypaper.

### Insight
I have all the libraries installed mentioned in #53 and I don't seem to find anything relevant for the _installable_ package either.

**Comment by tom-avilius** [comment]
Never mind, it is available in fedora through dnf.

**Comment by anufrievroman** [comment]
Thanks for the reporting. So, is it correct to say that waypaper can be installed as 
```
dnf install waypaper
```
Sorry, I am not Fedora, not sure how it works, but if that's the way I'd like to add it to the documentation.

**Comment by tom-avilius** [comment]
No wait.
I just ran `dnf info waypaper` and realized that it might not be in the official repository.
Look at the **output:**

Installed Packages
Name         : waypaper
Version      : 2.2
Release      : 1.fc40
Architecture : noarch
Size         : 236 k
Source       : waypaper-2.2-1.fc40.src.rpm
Repository   : @System
From repo    : copr:copr.fedorainfracloud.org:solopasha:hyprland
Summary      : GUI wallpaper setter for Wayland
URL          : https://github.com/anufrievroman/waypaper
License      : GPL-3.0-or-later
Description  : GUI wallpaper setter for Wayland and Xorg window managers. It works as
             : a frontend for popular wallpaper backends like swaybg, swww, wallutils and feh.

Available Packages
Name         : waypaper
Version      : 2.2
Release      : 1.fc40
Architecture : src
Size         : 559 k
Source       : None
Repository   : copr:copr.fedorainfracloud.org:solopasha:hyprland
Summary      : GUI wallpaper setter for Wayland
URL          : https://github.com/anufrievroman/waypaper
License      : GPL-3.0-or-later
Description  : GUI wallpaper setter for Wayland and Xorg window managers. It works as
             : a frontend for popular wallpaper backends like swaybg, swww, wallutils and feh.


### Conclusion
I must have enabled a third party repository earlier  _(Repository   : copr:copr.fedorainfracloud.org:solopasha:hyprland)_ that provides waypaper.

If you want to add it to the documentation you would have to mention adding the remote repository first. I would check on this more and tell you tomorrow.

**Comment by tom-avilius** [comment]
**These are the steps to install waypaper**
It is available in an external repository owned by Solopasha.
Link: [hyprland copr](https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/)

### To install 
`sudo dnf copr enable solopasha/hyprland`
then
`sudo dnf install wayapaper`

**Comment by anufrievroman** [comment]
Thank you, I updated the docs!
