### ISSUE TITLE
Blur text UI elements.

### ISSUE THREAD

**Issue by SherLock707** [anufrievroman/waypaper#77]
![image](https://github.com/user-attachments/assets/cfda5b1f-5650-4bde-9e0c-71a43ad641ca)
(Not sure if you can tell from above image)

Checked other GTK apps, their text look sharp.

Distro: `Arch Linux`
WM: `Hyprland 0.42.0-2`
Waypaper: `waypaper-git 2.3.r0.ged3e816-1`

Config:
> [Settings]
> language = en
> folder = ~/Pictures/wallpapers
> wallpaper = ~/Pictures/wallpapers/escape_velocity.png
> backend = swww
> monitors = All
> fill = fill
> sort = name
> color = #000000
> subfolders = False
> number_of_columns = 6
> swww_transition_type = wipe
> swww_transition_step = 120
> swww_transition_angle = 0
> swww_transition_duration = 2
> swww_transition_fps = 60
> post_command = ~/.config/hypr/scripts/Wallpaper_waypaper.sh
> show_hidden = False
> show_gifs_only = False
> use_xdg_state = False

_[Thank you for your amazing work]_

**Comment by anufrievroman** [comment]
I feel like it might be related to scaling, although I don't exactly see the blur. What's the monitor resolution and what's the scaling applied? I think the monitor related part of hyprland config might be useful to see as well. I personally have very similar system and everything seems fine.

**Comment by SherLock707** [comment]
Resolution: `LG Ultra-wide 3440x1440 @ 60 Hz in 34″ [External]`
hyprland conf: `monitor = HDMI-A-1,3440x1440@60, auto,1`
`text-scaling-factor = 1`

Rest of the apps look fine, so bit confused. (gparted, nwg-look, Thunar)

**Comment by SherLock707** [comment]
It was my Hyprland window rule issue. thanks.

`windowrulev2 = size 45.5% 70% ,class:(waypaper)`
Before:
![image](https://github.com/user-attachments/assets/142a0d34-b64d-4c0b-9f4a-da715f1114a6)

`windowrulev2 = size 45% 70% ,class:(waypaper)`
After:
![image](https://github.com/user-attachments/assets/f353f9c2-e27e-4953-b441-1a49fecabeaf)
