### ISSUE TITLE
Idea: Presets

### ISSUE THREAD

**Issue by Rdeisenroth** [anufrievroman/waypaper#79]
I have a script that randomly picks wallpapers every 5 minutes using `waypaper --backend swww --random` I do have some combination of wallpapers though that work particularily well and some that work very poor. I would love to have the ability to save and load presets, and ideally even an option to randomly select a preset like `waypaper --backend swww --random-preset`. (we could possibly even expand this with preset groups or playlists with custom delays and animations for each wallpaper, but one step at a time...)

A preset should store:
- the current wallpapers of each monitor
- the fill type
- the backend used
- possibly also animation settings

**Comment by anufrievroman** [comment]
Hi, thank you for the idea! To be honest, I feel like it's such a niche feature that it would be simpler to have it an external script that simply save your current config file as a "preset" in a separate folder, and then you can select it later with dmenu/rofi, and it replaces current config. 

I think I'll make a section in documentation for various handy scripts that do this kind of things. However, making it into the interface is more complicated, and we can't possibly have an interface section for every kind of complex behavior that is requested these days 😅
