### ISSUE TITLE
AUR is still targeting version 2.2

### ISSUE THREAD

**Issue by mylinuxforwork** [anufrievroman/waypaper#82]
Hi,

Waypaper is an awesome tool for wallpaper settings.

I want to use the great new features of 2.3 in my dotfiles. But I have seen that the AUR is still using 2.2: https://aur.archlinux.org/packages/waypaper

When is an update planned? Or what is the recommended installation method for Arch based distros?

**Comment by anufrievroman** [comment]
That's a great question. I don't control AUR repositories, so it's up to maintainer to update them. But there's also waypaper-git AUR which should buithe latest version.

**Comment by mylinuxforwork** [comment]
Yes. Was able to install it with waypaper-git. Never tried pipx.

Will try tomsend the maintainer a message and ask to update.

**Comment by mylinuxforwork** [comment]
@anufrievroman It has been updated to waypaper 2.3 https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=waypaper Will try it now.

**Comment by mylinuxforwork** [comment]
@anufrievroman Everything is working fine. Will update my dotfiles accordingly. I am also planning a special video about waypaper soon. It is really awesome.

**Comment by anufrievroman** [comment]
Thank you! I'll be happy to see you video :)
