### ISSUE TITLE
Multi-monitor support on all backends

### ISSUE THREAD

**Issue by anufrievroman** [anufrievroman/waypaper#85]
As we discussed with @CalfMoon in #84, there is no principal obstacle to supporting multi-monitors on all backends (i.e. swaybg and mpvpaper in addition to hyprpaper and swww that are already supporting). The only problem is that now we are using hyprpaper and swww backends to get information about plugged monitors. So, we need to write an independent function `get_monitor_names()` in `common.py` that would return plugged monitors on both Xorg and Wayland. Does anyone know a minimal and reliable way to get the monitor names? Some inspiration can be found in [Azote](https://github.com/nwg-piotr/azote/blob/master/azote/tools.py) but that's much too complex for such a simple task. Likewise, there are ways to get monitors via `xrandr` and `wayland-info`, but I wish there was something more simple...

**Comment by CalfMoon** [comment]
A python library could be used maybe? [screeninfo](https://pypi.org/project/screeninfo/) is what i found.

**Comment by anufrievroman** [comment]
Nice, that looks perfect for the job

**Comment by anufrievroman** [comment]
Okay, that's reimplemented. I'll need to test different backends once I get my hands on the second monitor. @CalfMoon maybe now you can uncomment the monitor support for mpvpaper. Thanks again for the recommendation!

**Comment by CalfMoon** [comment]
So I noticed that you completely removed the check to see which background it is before adding option, however I belive it should still be done as wallutils and feh don't support the feature and I don't think its good idea to add buttons for features that don't exist.

Also another thing the condition for all *_display() function is inside the function. Would it not be better to add the condition where the function is called?

**Comment by anufrievroman** [comment]
Yes, you are right, I missed that, thank you for PR.
