### ISSUE TITLE
Create --monitor user argument 

### ISSUE THREAD

**Issue by Decards** [anufrievroman/waypaper#94]
A nice thing to add would be an option for the randomize button not to display the same wallpapers on every monitors so each display would show a different wallpaper.  A nice thing to add would be an option for the randomize button not to display the same wallpapers on every monitors so each display would show a different wallpaper.

**Comment by Decards** [comment]
I mean you can do it in the gui but a Command line option to specify the monitor  randomized would allow me to make a daemon to randomize the wallpaper every X hours. 

something like: 

waypaper --randomize --monitor DP-1

**Comment by anufrievroman** [comment]
I actually recently reimplemented --random so that it randomizes for each monitor specified in the config. So, if in config it's `monitors = dp-1,dp-2` or something like that, then each monitor will get a unique random wallpaper. It's not yet published, but you can test it from the main branch.

**Comment by anufrievroman** [comment]
But in general I agree that there should be --monitor option. Let's keep this issue then as request for this option

**Comment by Decards** [comment]
When you say "f in config it's monitors = dp-1,dp-2", What config are you talking about ?

**Comment by anufrievroman** [comment]
The config.ini file in configs/waypaper or a state file if you are using that feature.

**Comment by WilliamG99** [comment]
> I actually recently reimplemented --random so that it randomizes for each monitor specified in the config. So, if in config it's `monitors = dp-1,dp-2` or something like that, then each monitor will get a unique random wallpaper. It's not yet published, but you can test it from the main branch.

This and the gui works great, unfortunately without a --monitor argument it overlooks vertical monitors. I have two different folders, one for landscape wallpapers and another for portrait. Just  --random cant differentiate which monitor needs to get a wallpaper from which folder. 

This is only a problem since I also would like to randomise my wallpaper every X hours.

**Comment by anufrievroman** [comment]
Ah, I see, interesting use case. Okay, I'll make the `--monitor` argument by the next version

**Comment by anufrievroman** [comment]
If you like, please :) it's not at all difficult, you only need to add a clause in __main__.py to account for the new user argument, you'll see several examples there. Plus add a description of the new argument in different languages (translation with ChatGPT is okay).

**Comment by anufrievroman** [comment]
Okay, I think the `--monitor` support is well implemented, so I'm closing this. Thank you all for discussions and contributions.
