### ISSUE TITLE
$wallpaper is empty

### ISSUE THREAD

**Issue by thecaprisun** [anufrievroman/waypaper#95]
I'm currently trying to set up pywal, I searched on reddit about using waypaper with it and i found [this](https://www.reddit.com/r/hyprland/comments/1ary4ac/how_can_i_get_pywal_to_detect_the_wallpaper_ive/), however when i try to run `echo $waypaper`, the output is completely empty.
Running Arch Linux, kernel 6.11.4, waypaper 2.3-1, hyprland 0.44.1-1
Thanks in advance.

EDIT: Backend is swww

EDIT 2: I tried installing it using pipx, same issue

**Comment by anufrievroman** [comment]
I'm not sure I entirely understand the problem. The $waypaper variable doesn't really exists (in the system), $wallpaper doesn't exist either. The $wallpaper is only used in the post_command option of the config. I.e. once you click on some wallpaper that command is executed, for example "post_command = echo $wallpaper" will just print the address of the newly selected wallpaper.

**Comment by thecaprisun** [comment]
> I'm not sure I entirely understand the problem. The $waypaper variable doesn't really exists (in the system), $wallpaper doesn't exist either. The $wallpaper is only used in the post_command option of the config. I.e. once you click on some wallpaper that command is executed, for example "post_command = echo $wallpaper" will just print the address of the newly selected wallpaper.

$waypaper was a typo, i meant $wallpaper
i did try using `pywal -i $wallpaper` in the post command, but it still didn't seem to work
anyways i switched from arch to freebsd, i guess i'll try again there.

**Comment by anufrievroman** [comment]
I can't really reproduce it. When I set `post_command = echo $wallpaper` if get exactly what's expected:
![image](https://github.com/user-attachments/assets/56617d3f-e4f0-4e44-8847-4530a1908fa4)
Are you sure that $wallpaper is empty and it's not some issue with the pywal?

**Comment by anufrievroman** [comment]
By the way, in that reddit thread I wrote "pywal" just as a guess, I think the actual command it "wal" or something. I mean I never used it, just wrote as example.

**Comment by thecaprisun** [comment]
> By the way, in that reddit thread I wrote "pywal" just as a guess, I think the actual command it "wal" or something. I mean I never used it, just wrote as example.

hm, i might've written that, the real command is wal tho, yeah. I'll check later

**Comment by anufrievroman** [comment]
I'll close this issue for now then. Feel free to open a new one if the problem persists.
