### ISSUE TITLE
Dependencies Missing from Arch PKGBUILD

### ISSUE THREAD

**Issue by Muhammad95959** [anufrievroman/waypaper#99]
I’m not sure if the author of this project is the same person who packages it for Arch, but the `python-imageio` and `python-screeninfo` packages are missing from the PKGBUILD

**Comment by Sneaky1000** [comment]
Seconding this. 

Traceback (most recent call last):
  File "/usr/bin/waypaper", line 5, in <module>
    from waypaper.__main__ import run
  File "/usr/lib/python3.12/site-packages/waypaper/__main__.py", line 10, in <module>
    from waypaper.app import App
  File "/usr/lib/python3.12/site-packages/waypaper/app.py", line 9, in <module>
    import imageio
ModuleNotFoundError: No module named 'imageio'

**Comment by Sneaky1000** [comment]
@Muhammad95959 Use `sudo pacman -S python-imageio`

**Comment by anufrievroman** [comment]
Hi, the maintainer of the arc packages [metak](https://aur.archlinux.org/account/metak) is not me (the maintainer of the waypaper). It usually takes him a while to package a new version and update the dependencies. So, I recommend pipx installation

**Comment by mmetak** [comment]
@anufrievroman 

I've updated both `waypaper` & `waypaper-git` in aur , but I'm mostly using stock Plasma so if anyone wants to take over these two packages in aur let me know.

**Comment by anufrievroman** [comment]
@mmetak thank you for your work on these packages, it helped this projects a lot!
If maintenance became bothersome at this point, feel free to open an issue, I'm sure someone will pick it up. Or maybe I'll finally understand how to setup the keys to commit to AUR :)
